services:
  kawa-script-runner:
    image: ${KAWA_SCRIPT_RUNNER_IMAGE_PATH}
    pull_policy: ${KAWA_SCRIPT_RUNNER_PULL_POLICY}
    ports:
      - ${KAWA_SCRIPT_RUNNER_EXTERNAL_PORT}:8815
    environment:
      KAWA_URL: ${KAWA_SERVER_URL}:8080
      KAWA_AUTOMATION_SERVER_AES_KEY: ${KAWA_RUNNER_AES_KEY}
    env_file:
      - path: kawa.script-runner.env
        required: false
  
  kawa-server:
    image: ${KAWA_SERVER_IMAGE_PATH}
    pull_policy: ${KAWA_SERVER_PULL_POLICY}
    ports:
      - ${KAWA_SERVER_EXTERNAL_PORT}:8080
    volumes:
      - kawadata:/home/kawa/user-files
      - ./server.crt:/home/kawa/server.crt
      - ./server.key:/home/kawa/server.key
    environment:
      KAWA_GLOBAL_RUNNER_AES_KEY: ${KAWA_RUNNER_AES_KEY}
      KAWA_DEFAULT_RUNNER_AES_KEY: ${KAWA_RUNNER_AES_KEY}
      KAWA_LANGCHAIN_CONFIGURATION: ${KAWA_SERVER_LANGCHAIN_CONFIGURATION}
      KAWA_FILE_STORE_DIRECTORY: /home/kawa/user-files/local
      KAWA_SMTP_USERNAME: ${KAWA_SMTP_USERNAME}
      KAWA_SMTP_PASSWORD: ${KAWA_SMTP_PASSWORD}
      KAWA_PATH_TO_SERVER_CERTIFICATE: /home/kawa/server.crt
      KAWA_PATH_TO_SERVER_PRIVATE_KEY: /home/kawa/server.key
      KAWA_BYPASS_VAULT: true
      KAWA_HTTPS: ${KAWA_SERVER_HTTPS}
      KAWA_OAUTH2_CLIENT_SECRET: ${KAWA_OAUTH2_CLIENT_SECRET}
      KAWA_POSTGRES_JDBC_URL: ${KAWA_POSTGRES_JDBC_URL}
      KAWA_CLICKHOUSE_JDBC_URL: ${KAWA_CLICKHOUSE_JDBC_URL}
      KAWA_ACCESS_TOKEN_SECRET: ${KAWA_ACCESS_TOKEN_SECRET}
      KAWA_REFRESH_TOKEN_SECRET: ${KAWA_REFRESH_TOKEN_SECRET}
      KAWA_ENCRYPTION_IV: ${KAWA_ENCRYPTION_IV}
      KAWA_ENCRYPTION_KEY: ${KAWA_ENCRYPTION_KEY}
      KAWA_CLICKHOUSE_IS_POST_23_DOT_8: true
      KAWA_CLICKHOUSE_ALLOW_LIVE_CONNECT: true
      KAWA_CLICKHOUSE_INTERNAL_DATABASE: ${KAWA_CLICKHOUSE_INTERNAL_DATABASE}
      KAWA_WAREHOUSE_TYPE: ${KAWA_WAREHOUSE_TYPE}
      KAWA_SNOWFLAKE_USER: ${KAWA_SNOWFLAKE_USER}
      KAWA_SNOWFLAKE_PASSWORD: ${KAWA_SNOWFLAKE_PASSWORD}
      KAWA_SNOWFLAKE_WAREHOUSE: ${KAWA_SNOWFLAKE_WAREHOUSE}
      KAWA_SNOWFLAKE_ACCOUNT: ${KAWA_SNOWFLAKE_ACCOUNT}
      KAWA_SNOWFLAKE_WRITER_USER: ${KAWA_SNOWFLAKE_WRITER_USER}
      KAWA_SNOWFLAKE_WRITER_PASSWORD: ${KAWA_SNOWFLAKE_WRITER_PASSWORD}
      KAWA_SNOWFLAKE_WRITER_WAREHOUSE: ${KAWA_SNOWFLAKE_WRITER_WAREHOUSE}
      KAWA_SNOWFLAKE_WRITER_ACCOUNT: ${KAWA_SNOWFLAKE_WRITER_ACCOUNT}
      KAWA_SNOWFLAKE_WRITER_CATALOG: ${KAWA_SNOWFLAKE_WRITER_CATALOG}
      KAWA_SNOWFLAKE_WRITER_SCHEMA: ${KAWA_SNOWFLAKE_WRITER_SCHEMA}
      KAWA_SNOWFLAKE_WRITER_TABLE_PREFIX: KAWA__
      KAWA_ENTITY_CACHE_IS_ENABLED: true

    env_file:
      - path: kawa.server.env
        required: false
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: 5

  clickhouse:
    image: "clickhouse/clickhouse-server:24.8.12-alpine"
    profiles:
      - clickhouse
    volumes:
      - clickhousedata:/var/lib/clickhouse
      - /tmp/clickhouse-server:/var/log/clickhouse-server
      - ./assets/users.d:/etc/clickhouse-server/users.d
      - ./assets/config.d:/etc/clickhouse-server/config.d
    ports:
      - ${CLICKHOUSE_EXTERNAL_PORT}:8123
      - ${CLICKHOUSE_EXTERNAL_TCP_PORT}:9000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - path: clickhouse.env
        required: false

  postgres:
    image: "postgres:13.12-alpine"
    environment:
      POSTGRES_USER: ${KAWA_DB_USER}
      POSTGRES_PASSWORD: ${KAWA_DB_PASSWORD}
      POSTGRES_DB: kawa
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:5432
    env_file:
      - path: postgres.env
        required: false

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      device: ${MOUNT_DIRECTORY}/pgdata
      o: bind
  clickhousedata:
    driver: local
    driver_opts:
      type: none
      device: ${MOUNT_DIRECTORY}/clickhousedata
      o: bind
  kawadata:
    driver: local
    driver_opts:
      type: none
      device: ${MOUNT_DIRECTORY}/kawadata
      o: bind

networks:
  default:
    name: ${KAWA_DOCKER_COMPOSE_NETWORK_NAME}
    driver: ${KAWA_DOCKER_COMPOSE_NETWORK_DRIVER}
