services:
  kawa-script-runner:
    image: ${KAWA_SCRIPT_RUNNER_IMAGE_PATH}
    pull_policy: ${KAWA_SCRIPT_RUNNER_PULL_POLICY}
    ports:
      - ${KAWA_SCRIPT_RUNNER_EXTERNAL_PORT}:8815
    environment:
      KAWA_URL: ${KAWA_SERVER_URL}:${KAWA_SERVER_EXTERNAL_PORT}
      KAWA_AUTOMATION_SERVER_AES_KEY: ${KAWA_RUNNER_AES_KEY}
    env_file:
      - path: kawa.script-runner.env
        required: false

  kawai:
    image: ${KAWA_AGENT_RUNNER_IMAGE_PATH}
    pull_policy: ${KAWA_AGENT_RUNNER_PULL_POLICY}
    profiles:
      - agent-runner
    environment:
      KAWA_API_URL: ${KAWA_SERVER_URL}:${KAWA_SERVER_EXTERNAL_PORT}
      KAWAI_PORT: ${KAWA_AGENT_RUNNER_EXTERNAL_PORT}
      CHROMADB_HOST: ${KAWA_AGENT_RUNNER_CHROMADB_HOST}
      CHROMADB_PORT: ${KAWA_AGENT_RUNNER_CHROMADB_PORT}
      OPENAI_API_KEY: ${KAWA_AGENT_RUNNER_OPENAI_API_KEY}
      TAVILY_API_KEY: ${KAWA_AGENT_RUNNER_TAVILY_API_KEY}
      MAILGUN_API_KEY: ${KAWA_AGENT_RUNNER_MAILGUN_API_KEY}
      MAILGUN_DOMAIN: ${KAWA_AGENT_RUNNER_MAILGUN_DOMAIN}
      LLAMA_CLOUD_API_KEY: ${KAWA_AGENT_RUNNER_LLAMA_CLOUD_API_KEY}
      ANTHROPIC_API_KEY: ${KAWA_AGENT_RUNNER_ANTHROPIC_API_KEY}
    ports:
      - ${KAWA_AGENT_RUNNER_EXTERNAL_PORT}:8001
    env_file:
      - path: kawa.agent-runner.env
        required: false

  kawa-server:
    image: ${KAWA_SERVER_IMAGE_PATH}
    pull_policy: ${KAWA_SERVER_PULL_POLICY}
    ports:
      - ${KAWA_SERVER_EXTERNAL_PORT}:8080
    volumes:
      - kawadata:/home/kawa/user-files
      - ./server.crt:/home/kawa/server.crt
      - ./server.key:/home/kawa/server.key
    environment:
      KAWA_LANGCHAIN_CONFIGURATION: ${KAWA_SERVER_LANGCHAIN_CONFIGURATION}
      KAWA_FILE_STORE_DIRECTORY: /home/kawa/user-files/local
      KAWA_SMTP_USERNAME: ${KAWA_SMTP_USERNAME}
      KAWA_SMTP_PASSWORD: ${KAWA_SMTP_PASSWORD}
      KAWA_PATH_TO_SERVER_CERTIFICATE: /home/kawa/server.crt
      KAWA_PATH_TO_SERVER_PRIVATE_KEY: /home/kawa/server.key
      KAWA_BYPASS_VAULT: true
      KAWA_HTTPS: ${KAWA_SERVER_HTTPS}
      KAWA_OAUTH2_CLIENT_SECRET: ${KAWA_OAUTH2_CLIENT_SECRET}
      KAWA_POSTGRES_JDBC_URL: ${KAWA_POSTGRES_JDBC_URL}
      KAWA_CLICKHOUSE_JDBC_URL: ${KAWA_CLICKHOUSE_JDBC_URL}
      KAWA_ACCESS_TOKEN_SECRET: ${KAWA_ACCESS_TOKEN_SECRET}
      KAWA_REFRESH_TOKEN_SECRET: ${KAWA_REFRESH_TOKEN_SECRET}
      KAWA_ENCRYPTION_IV: ${KAWA_ENCRYPTION_IV}
      KAWA_ENCRYPTION_KEY: ${KAWA_ENCRYPTION_KEY}
      KAWA_CLICKHOUSE_IS_POST_23_DOT_8: true
      KAWA_CLICKHOUSE_ALLOW_LIVE_CONNECT: true
      KAWA_CLICKHOUSE_INTERNAL_DATABASE: ${KAWA_CLICKHOUSE_INTERNAL_DATABASE}
    env_file:
      - path: kawa.server.env
        required: false
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: 5

  clickhouse:
    image: "clickhouse/clickhouse-server:24.7.2-alpine"
    volumes:
      - clickhousedata:/var/lib/clickhouse
      - /tmp/clickhouse-server:/var/log/clickhouse-server
      - ./assets/users.d:/etc/clickhouse-server/users.d
      - ./assets/config.d:/etc/clickhouse-server/config.d
    ports:
      - ${CLICKHOUSE_EXTERNAL_PORT}:8123
    env_file:
      - path: clickhouse.env
        required: false

  postgres:
    image: "postgres:13.12-alpine"
    environment:
      POSTGRES_USER: ${KAWA_DB_USER}
      POSTGRES_PASSWORD: ${KAWA_DB_PASSWORD}
      POSTGRES_DB: kawa
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:5432
    env_file:
      - path: postgres.env
        required: false

  chromadb:
    image: chromadb/chroma:0.5.5
    volumes:
      - chromadbdata:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-TRUE}
    ports:
      - 8000:8000
    env_file:
      - path: chromadb.env
        required: false

volumes:
  chromadbdata:
    driver: local
    driver_opts:
      type: none
      device: ${MOUNT_DIRECTORY}/chromadbdata
      o: bind
  pgdata:
    driver: local
    driver_opts:
      type: none
      device: ${MOUNT_DIRECTORY}/pgdata
      o: bind
  clickhousedata:
    driver: local
    driver_opts:
      type: none
      device: ${MOUNT_DIRECTORY}/clickhousedata
      o: bind
  kawadata:
    driver: local
    driver_opts:
      type: none
      device: ${MOUNT_DIRECTORY}/kawadata
      o: bind

networks:
  default:
    name: ${KAWA_DOCKER_COMPOSE_NETWORK_NAME}
    driver: ${KAWA_DOCKER_COMPOSE_NETWORK_DRIVER}
