#!/bin/bash
set -e

: "${POSTGRES_USER:?Missing POSTGRES_USER}"
: "${KAWA_WORKFLOW_DB_NAME:?Missing KAWA_WORKFLOW_DB_NAME}"
: "${KAWA_WORKFLOW_SCHEMA_NAME:?Missing KAWA_WORKFLOW_SCHEMA_NAME}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<-EOSQL
  CREATE DATABASE "$KAWA_WORKFLOW_DB_NAME";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$KAWA_WORKFLOW_DB_NAME" <<-EOSQL
  CREATE SCHEMA IF NOT EXISTS "$KAWA_WORKFLOW_SCHEMA_NAME";
EOSQL
